steps:
#install dependencies, audit dependencies and run tests
- name: node
  entrypoint: npm
  args: ['install']
  id: install dependencies
- name: node
  entrypoint: npm
  args: ['test']
  id: test

#build container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/node-app/node-app:${COMMIT_SHA}', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/node-app/node-app','-f', 'Dockerfile']
  id: build

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/node-app/node-app:${COMMIT_SHA}']
  id: push

# Create release in Google Cloud Deploy
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args: 
    [
      "beta", "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "node-app-pipeline",
      "--region", "us-central1",
      "--annotations", "commitId=${REVISION_ID}",
      "--images", "node-app=us-central1-docker.pkg.dev/$PROJECT_ID/node-app/node-app:${COMMIT_SHA}"
    ]