apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  template:
    spec:
      containers:
          - name: node-app
            env:
              - name: SITE_NAME
                value: "Population Stats Staging"